version: "3"
services:
  app:
    build: .
    command: yarn dev
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/node_app
      - nodemodules:/node_app/node_modules

volumes:
  nodemodules: {}
